# Netlify configuration file
# This is an alternative approach for hosting the site

[build]
  command = "npm run build"
  publish = "dist"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
